### PR TITLE
Add two off-topic cases

### PR DESCRIPTION
**Pull request by alpereira7**

### CODE REVIEW

**Comment by alpereira7** [comment]
@gunr2171 I cant's see where is a conflict...

**Comment by gunr2171** [comment]
@rschrieken snuck in a commit 2 days ago. Rebase your branch onto our master and that should fix itself.

**Comment by gunr2171** [comment]
Uh, well actually, looking that this more...

So you've got 2 commits right now: "Update Questions" and "Create Questions".

As seen in the [history of master](https://github.com/SO-Close-Vote-Reviewers/auto-comments/commits/master), the "Create Questions" commit already exists (and was done [24 days ago](https://github.com/SO-Close-Vote-Reviewers/auto-comments/pull/51)).

However, because I chose the "rebase" option for the PR, the commit ID got modified (`64730ef` in your master branch, `e6c0abd` in your master branch), and that's why this PR is presenting both commits as "new".

Uh, so yeah. I'm a) not sure why the commit Id changed (maybe it's so that GitHub can record who the person was who did the PR in addition to the original committer), and b) not sure what pattern I should do from now.

I guess the short version is to rebase your branch onto master and remove your "different" "Create questions" commit. In future, it might be better to delete your forked branch after completing a PR rather than re-using an already "merged" branch.

Still open to suggestions though.

**Comment by makyen** [comment]
After a PR is merged, it's good (necessary) to always `pull` from the main repository, as doing so should pick-up any changes that were needed in order to merge. If you do so, then it's possible to continue to use the same branch (if rebased to the main repository's master, which may be a different commit). However, I consider it "normal" to delete the branch once it's been merged, even if you want to recreate one with an identical name, but that assumes you're not using the "master" branch in your repository for the PR.

A contributing issue is that you are working in the "master" branch in your repository. Unless there's a need to work in the master branch, it's usually much cleaner to use a separate branch for each PR. If you are going to use your "master" branch, then you *must* pull *and* reset your master branch to the same commit as the main repository's master after a PR is merged. For the edits you've done (i.e. a single edit per PR), it's probably OK to use your master branch, but you will need to make sure that your master branch ends up on the same commit as the main repository's master after every PR is merged.

If I were you, to resolve this, I'd:
1. pull
2. Create a new branch (pick name) at the main repository's master commit
3. `git cherry-pick` the "Update questions.md" commit onto the newly created branch.
4. Submit a new PR from the newly created branch.

After the PR is merged, I'd (i.e. again, if I was you, working in your repository):
1. delete the branch from the PR page
2. pull
3. prune
4. reset -hard your master branch to the commit that is the master branch in the main repository.

Actually, there are multiple ways to handle it after the merge. One alternative is to delete your repository and re-clone from the main repository.

Looks like we (repository owners) can resolve the issues from here, though. To do so, I'm going to create a new branch prior to the prior PR and cherry-pick the new commit.

**Comment by makyen** [comment]
@alpereira7 At this point, please verify that your repository's master is on the same commit as this repository's master. It will be a different "Update questions.md" commit than originally existed in your repository (the `cherry-pick` changes the commit).

**Pull request merged**
