### PR TITLE
Suggested boilerplate text for gender assumptions

### PR DESCRIPTION
**Pull request by halfer**
I tend to use the following text whenever a question refers to readers as "Gents" or "Gentlemen" (or other obviously gendered greeting).

I did think of switching women to "non-men" but that sounded clumsy to my ears, so I suggest this as a rough first version.

(I can't see why this would not merge automatically, I branched from master just now?)

### CODE REVIEW

**Comment by halfer** [comment]
Ah, I think I have not merged in your master, only my own. Fixing...

**Comment by gunr2171** [comment]
I'm not sure if this should be a commonly-used auto comment, and instead just edit the post without the fanfare.

**Comment by halfer** [comment]
@gunr2171, your version is much better, thanks. I will merge that into my own copy.

I have pinged SO CVR with a linky to here, in case anyone else wants to chime in with yes/no/maybe.

**Comment by halfer** [comment]
I've modified it again, as I liked your point that it's not just women asking for gender neutral language:

> Hi there. A number of folks in our community sometimes say that every time they see gendered assumptions about software engineers, they worry about people feeling excluded. I wonder, could you try to avoid adding male-oriented greetings and pronouns in your posts, so as to make for a more welcoming environment? Thank you.

I wondered, in retrospect, whether the "open mind" bit of your version might be (wrongly) interpreted as hostile, so I have kept the gentler parts of my original.

When I get a moment I will ask for feedback again from other folks. I like to comment, since not doing so may not change a gendered behaviour, but I appreciate opinions will vary on that.

**Comment by gunr2171** [comment]
You'll also need to resolve the merge conflict before I can finish this PR.

**Comment by halfer** [comment]
I've resolved conflicts and updated to the version of the text I suggested above.

**Comment by gunr2171** [comment]
@halfer there's still merge conflicts.

**Comment by halfer** [comment]
@gunr2171: I've resolved conflicts again, I think new ones must have appeared since 21st Aug! Great if you can merge it down.

**Pull request merged**
