### PR TITLE
bumping old posts

### PR DESCRIPTION
**Pull request by yvettec**
Better guidance for bumping old posts.

### CODE REVIEW

**Comment by halfer** [comment]
> Do not make minor edits to old posts.

I wonder if this can be softed a bit? I recall that I've taken too much umbrage in the past, in response to a comment that appeared to be giving me an order. This seems to be written in the same way. How about any of these:

> Please do not make minor edits to old posts.

or 

> The community tends to prefer it if minor edits are not made to old posts.

**Comment by yvettec** [comment]
Hi Halfer,
That's fine, make any edits you see fit. That's the purpose of them, to be improved. 
Thanks for the feedback.
Cheers

**Comment by gunr2171** [comment]
@yvettec just a note, I can't proceed on merging this until the conflicts are resolved.

**Comment by halfer** [comment]
@yvettec: ah, of course, you were editing this, not adding it. Apologies! Good idea, I will ponder how it can be improved.

**Pull request closed without merging**
